---
# Where the receipts are stored
# Receipts should be simple text files
receipts_path: "txt"

# Market names roughly ordered by likelyhood.
# Can contain market locations for fuzzy parsing
stores:
  Biggby:
      - biggby
      - b i g g b y
  Target:
      - target
  Dicks Sporting Goods:
      - Dick's Sporting Goods
      - Dicks Sporting Goods
      - Sporting Goods
  Spartys Wonders:
      - Sparty's Wonders
      - Wonders
  Spartys Engineering:
      - Sparty's Engineering
      - Engineering
  Aroma Cafe:
      - AROMA CAFE
  Jimmy Johns:
      - jimmy
      - johns
  Starbucks:
      - starbucks
  Shell:
      - shell
  No Thai:
      - thai

  Downtown Parking LLC:
      - Downtown Parking LLC

  Lauren Carande:
      - LAUREN CARANDE
      - L A U R E N  C A R A N D E
      - CARANDE
      - C A R A N D E
  
  Walmart:
      - Walmart
      - WaImart

  Stonewood Grill And Tavern:
      - STONEWOOD
      - S T O N E W O O D
      - GRILL & TAVERN
      - G R I L L & T A V E R N
      - GROUPER
      - FILET
      - MUSSELS


  Lorem Shop:
      - LOREM SHOP
      - L O R E M S H O P
      - euis
      - Knonuy
      - magna
      - dolore





# Sum keys roughly ordered by likelihood.
sum_keys:
  - total
  - payment
  - amount
  - tendered
  - usd

sum_format: '(\d+(\.\s?|,\s?|[^a-zA-Z\d])\d{2})|(\$\d+(\.\s?|,\s?|[^a-zA-Z\d])\d{2})'

# Matches dates like 19.08.15, 19. 08. 2015 and 08/19/2015
# date_format: '(.*?(?P<date>(\d{2,4}(\.\s?|[^a-zA-Z\d])\d{2}(\.\s?|[^a-zA-Z\d])(20)?1[3-6]))\s+'

