---
# Where the receipts are stored
# Receipts should be simple text files
receipts_path: "txt"

# Market names roughly ordered by likelyhood.
# Can contain market locations for fuzzy parsing
stores:
  Biggby:
      - biggby
      - b i g g b y
  Target:
      - target

# Sum keys roughly ordered by likelihood.
sum_keys:
  - total
  - payment

sum_format: '\d+(\.\s?|,\s?|[^a-zA-Z\d])\d{2}|'$'\d+(\.\s?|,\s?|[^a-zA-Z\d])\d{2}

# Matches dates like 19.08.15, 19. 08. 2015 and 08/19/2015
# date_format: '(.*?(?P<date>(\d{2,4}(\.\s?|[^a-zA-Z\d])\d{2}(\.\s?|[^a-zA-Z\d])(20)?1[3-6]))\s+'

